### ISSUE TITLE
Choose Message-Sending Method

### ISSUE THREAD

**Issue by jworkman01** [rhay-repo/notifications-for-sporting-events#2]
Choose which method we will use to send out our notifications

**Comment by rhay-repo** [comment]
Options:
- Web App interface that is updated every so often
- [https://pypi.org/project/signal-cli-rest-api/](Signal REST API)
- [https://rapidapi.com/collection/free-sms-apis](other free options)

**Comment by jworkman01** [comment]
We have decided to go along with a web app interface, so for now there will not actually be any mobile notifications, only notifications on the web app, but if we have time we will try to implement mobile notifications as well.
